# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            sigh.wtf
tagline:          'Security Randoms'
description:      'Random on security'
url:              http://sigh.wtf
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Google services
google_analytics: UA-97315479-1